### ISSUE TITLE
Manual de usuario

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#18]
* Requisitos de la app
* Instalación

**Comment by rms1005** [comment]
Add help contents #18

**Comment by rms1005** [comment]
Add video-tutorials #18

**Comment by rms1005** [comment]
Document Manual de usuario #18

**Comment by rms1005** [comment]
Minor changes #18

**Comment by rms1005** [comment]
Minor fix #18

**Comment by rms1005** [comment]
Improve help #18

**Comment by rms1005** [comment]
Improve display of videos #18

**Comment by rms1005** [comment]
Improve display of videos #18
