### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by dhm1002** [dpr1005/GESPRO_PracticaGestionTareas_2021#21]

**Comment by dhm1002** [comment]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by dhm1002** [comment]
![image](https://user-images.githubusercontent.com/74184622/99657238-333f2200-2a5e-11eb-8d4e-6f5513087af3.png)
![image](https://user-images.githubusercontent.com/74184622/99657255-376b3f80-2a5e-11eb-9dad-0aaa68322834.png)
![image](https://user-images.githubusercontent.com/74184622/99657271-3c2ff380-2a5e-11eb-9020-78209f8b10ca.png)
![image](https://user-images.githubusercontent.com/74184622/99657284-40f4a780-2a5e-11eb-8544-a38af1f258ea.png)

**Comment by dhm1002** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees

**Comment by dpuenteramirez** [comment]
![imagen](https://user-images.githubusercontent.com/74184545/99673780-82dd1800-2a75-11eb-9650-5e47242881b9.png)

![imagen](https://user-images.githubusercontent.com/74184545/99673780-82dd1800-2a75-11eb-9650-5e47242881b9.png)
