### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by rms1005** [dpr1005/GESPRO_PracticaGestionTareas_2021#25]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by dhm1002** [comment]
![image](https://user-images.githubusercontent.com/74184622/99711423-0ca2da80-2aa2-11eb-855e-18dc39f8ac76.png)
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry

**Comment by dhm1002** [comment]
Fix exception  wit vectors  in API < 21 #25
