### ISSUE TITLE
Pasar anexos a latex

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#27]
- [x] Plan de proyecto software
- [x] Esoecificación de Requisitos
- [ ] Especificación de diseño
- [x] Nabyak del programador
- [x] Manual de usuario

Expresión regular para corregir las referencias:

    Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
    Reemplazar por: \\citep{\2}

Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

    Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
    Reemplazar por: \\imagen{\2}{descripción...}

Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by dhm1002** [comment]
Convert annex D to latex #27

**Comment by dhm1002** [comment]
Convert annex E to latex #27

**Comment by dhm1002** [comment]
Convert annex B to latex #27

**Comment by dhm1002** [comment]
Convert annex A to latex #27
