### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by dhm1002** [dpr1005/GESPRO_PracticaGestionTareas_2021#31]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by rms1005** [comment]
Add javadoc #31

**Comment by rms1005** [comment]
Document Manual Programador #31

**Comment by rms1005** [comment]
Convert annex C to latex #31
