### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#34]
* Código fuente app
    * Ejecutable app
    * Herramientas
        * Plataforma de desarrollo del algoritmo
        * Herramienta de conteo de abejas
    * Documentación
        * Memoria
        * Anexos
        * JavaDoc
    * Dataset de videos

**README**

    * Repositorio GoBees
    * Repositorio prototipos
    * Repositorio dependencia OpenCV

**Comment by rms1005** [comment]
Add cd cover #34

**Comment by rms1005** [comment]
Add cd cover #34
