### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by rms1005** [dpr1005/GESPRO_PracticaGestionTareas_2021#35]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by dhm1002** [comment]
Add Google Play Link #35

**Comment by dhm1002** [comment]
Update .gitignore #35

**Comment by dhm1002** [comment]
Finish website #35

**Comment by dhm1002** [comment]
Minor fixes and compress imgs #35

**Comment by dhm1002** [comment]
Minor changes #35

**Comment by dhm1002** [comment]
Add docs link #35

**Comment by dhm1002** [comment]
http://gobees.io/
