### ISSUE TITLE
Imprimir memoria

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#38]
La memoria ha de estar encuadernada en formato:

    

- Libro cosido,
- Libro pegado,
- Libro con grapa de canto metálico prensada.
- Revista de tapa dura y grapa.

No se deben usar formatos de encuadernación de tornillos, espirales, canutillos y similares.

**Comment by dhm1002** [comment]
Finish report #38
