### ISSUE TITLE
Finalizar documentación proyecto [ESP-EN]

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#40]
Terminar la documentación del proyecto en los siguientes idiomas:
- Español, castellano internacional.
- Inglés, EEUU.

**Comment by dhm1002** [comment]
Commit a #40

**Comment by dhm1002** [comment]
Add chinese language #40

**Comment by rms1005** [comment]
Document Documentation #40
