### ISSUE TITLE
Celebrar fin de proyecto con una fiesta

### ISSUE THREAD

**Issue by dhm1002** [dpr1005/GESPRO_PracticaGestionTareas_2021#42]
Pero con medidas de seguridad que el covid no está invitado

**Comment by dpuenteramirez** [comment]
Buscar localización

**Comment by dpuenteramirez** [comment]
Contratar catering

**Comment by dpuenteramirez** [comment]
Reservar localización

**Comment by dpuenteramirez** [comment]
Celebrar el fin de la carrera, que para nada ha sido un sufrimiento
