### ISSUE TITLE
Integración de SonarQube

### ISSUE THREAD

**Issue by dpuenteramirez** [dpr1005/GESPRO_PracticaGestionTareas_2021#8]
Aunque ya se cuenta con code climate y codecov entre los servicios de integración continua para evaluar la calidad del código, sería recomendable pasar también los motores de análisis de SonarQube ya que es el que utilizará el tribunal para evaluar el TFG.

https://sonarqube.com/
https://github.com/integrations/sonarqube
https://docs.travis-ci.com/user/sonarqube/

**Comment by dhm1002** [comment]
Integrate SonarQube #8

**Comment by dhm1002** [comment]
Minor fix SonarQube #8

**Comment by dhm1002** [comment]
Minor fixes #8

**Comment by dhm1002** [comment]
Finish SonarQube integration  #8
